title: Yanjun (Ian) Lyu
description: Your tagline or research interests
url: "https://Ianlyu.github.io"

# Try themes
# theme: jekyll-theme-cayman
theme: jekyll-theme-minimal


# Addons（GitHub Pages 原生支持）
plugins:
  - jekyll-feed      # RSS
  - jekyll-sitemap   # map
  - jekyll-seo-tag   # SEO

# Head（对应下面将要创建的页面）
header_pages:
  - About.md
  - Story.md
  - Publications.md
  - CV.md
