title: Yanjun (Ian) Lyu
description: Your tagline or research interests
url: "https://Ianlyu.github.io"

# Try themes
# theme: jekyll-theme-cayman
# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Addons（GitHub Pages 原生支持）
plugins:
  - jekyll-feed      # RSS
  - jekyll-sitemap   # map
  - jekyll-seo-tag   # SEO

# Head（对应下面将要创建的页面）
header_pages:
  - About.md
  - Story.md
  - Publications.md
  - CV.md
